// A broad, practical list of world languages for the Settings "Language"
// dropdown -- major world languages plus widely-spoken regional ones.
// `code` is used as the cache key and as the {language} name sent to the
// translation API is `label` (in English), which reads more reliably for
// Claude than a bare ISO code.
export type Language = {
  code: string;
  label: string;
};

export const LANGUAGES: Language[] = [
  { code: "en", label: "English" },
  { code: "ar", label: "Arabic" },
  { code: "ckb", label: "Kurdish (Sorani)" },
  { code: "kmr", label: "Kurdish (Kurmanji)" },
  { code: "tr", label: "Turkish" },
  { code: "fa", label: "Farsi (Persian)" },
  { code: "fr", label: "French" },
  { code: "es", label: "Spanish" },
  { code: "de", label: "German" },
  { code: "zh", label: "Chinese (Simplified)" },
  { code: "zh-TW", label: "Chinese (Traditional)" },
  { code: "ja", label: "Japanese" },
  { code: "ko", label: "Korean" },
  { code: "hi", label: "Hindi" },
  { code: "ur", label: "Urdu" },
  { code: "ru", label: "Russian" },
  { code: "pt", label: "Portuguese" },
  { code: "pt-BR", label: "Portuguese (Brazil)" },
  { code: "it", label: "Italian" },
  { code: "sw", label: "Swahili" },
  { code: "nl", label: "Dutch" },
  { code: "pl", label: "Polish" },
  { code: "uk", label: "Ukrainian" },
  { code: "el", label: "Greek" },
  { code: "he", label: "Hebrew" },
  { code: "th", label: "Thai" },
  { code: "vi", label: "Vietnamese" },
  { code: "id", label: "Indonesian" },
  { code: "ms", label: "Malay" },
  { code: "tl", label: "Filipino (Tagalog)" },
  { code: "bn", label: "Bengali" },
  { code: "pa", label: "Punjabi" },
  { code: "ta", label: "Tamil" },
  { code: "te", label: "Telugu" },
  { code: "mr", label: "Marathi" },
  { code: "gu", label: "Gujarati" },
  { code: "kn", label: "Kannada" },
  { code: "ml", label: "Malayalam" },
  { code: "si", label: "Sinhala" },
  { code: "ne", label: "Nepali" },
  { code: "my", label: "Burmese" },
  { code: "km", label: "Khmer" },
  { code: "lo", label: "Lao" },
  { code: "ka", label: "Georgian" },
  { code: "hy", label: "Armenian" },
  { code: "az", label: "Azerbaijani" },
  { code: "uz", label: "Uzbek" },
  { code: "kk", label: "Kazakh" },
  { code: "ky", label: "Kyrgyz" },
  { code: "tg", label: "Tajik" },
  { code: "tk", label: "Turkmen" },
  { code: "mn", label: "Mongolian" },
  { code: "ps", label: "Pashto" },
  { code: "sd", label: "Sindhi" },
  { code: "am", label: "Amharic" },
  { code: "so", label: "Somali" },
  { code: "ha", label: "Hausa" },
  { code: "yo", label: "Yoruba" },
  { code: "ig", label: "Igbo" },
  { code: "zu", label: "Zulu" },
  { code: "xh", label: "Xhosa" },
  { code: "af", label: "Afrikaans" },
  { code: "st", label: "Sesotho" },
  { code: "sn", label: "Shona" },
  { code: "rw", label: "Kinyarwanda" },
  { code: "ny", label: "Chichewa" },
  { code: "mg", label: "Malagasy" },
  { code: "om", label: "Oromo" },
  { code: "ti", label: "Tigrinya" },
  { code: "rn", label: "Kirundi" },
  { code: "wo", label: "Wolof" },
  { code: "ff", label: "Fula" },
  { code: "sq", label: "Albanian" },
  { code: "sr", label: "Serbian" },
  { code: "hr", label: "Croatian" },
  { code: "bs", label: "Bosnian" },
  { code: "mk", label: "Macedonian" },
  { code: "bg", label: "Bulgarian" },
  { code: "ro", label: "Romanian" },
  { code: "hu", label: "Hungarian" },
  { code: "cs", label: "Czech" },
  { code: "sk", label: "Slovak" },
  { code: "sl", label: "Slovenian" },
  { code: "lt", label: "Lithuanian" },
  { code: "lv", label: "Latvian" },
  { code: "et", label: "Estonian" },
  { code: "fi", label: "Finnish" },
  { code: "sv", label: "Swedish" },
  { code: "no", label: "Norwegian" },
  { code: "da", label: "Danish" },
  { code: "is", label: "Icelandic" },
  { code: "ga", label: "Irish" },
  { code: "cy", label: "Welsh" },
  { code: "mt", label: "Maltese" },
  { code: "eu", label: "Basque" },
  { code: "ca", label: "Catalan" },
  { code: "gl", label: "Galician" },
  { code: "lb", label: "Luxembourgish" },
  { code: "yue", label: "Cantonese" },
  { code: "haw", label: "Hawaiian" },
  { code: "sm", label: "Samoan" },
  { code: "mi", label: "Maori" },
  { code: "to", label: "Tongan" },
  { code: "fj", label: "Fijian" },
  { code: "ht", label: "Haitian Creole" },
  { code: "qu", label: "Quechua" },
  { code: "gn", label: "Guarani" },
  { code: "ay", label: "Aymara" },
  { code: "jv", label: "Javanese" },
  { code: "su", label: "Sundanese" },
  { code: "ceb", label: "Cebuano" },
  { code: "ilo", label: "Ilocano" },
  { code: "yi", label: "Yiddish" },
  { code: "co", label: "Corsican" },
  { code: "fy", label: "Frisian" },
  { code: "gd", label: "Scottish Gaelic" },
  { code: "hmn", label: "Hmong" },
  { code: "la", label: "Latin" },
  { code: "eo", label: "Esperanto" },
];

export function languageLabel(code: string): string {
  return LANGUAGES.find((l) => l.code === code)?.label ?? code;
}
